platform :ios, '9.0'

target 'MVVMPractice' do
  use_frameworks!

#pod 'AppMusic', :path => 'DevelopmentPods/AppMusic'

pod 'Fate', :path => 'DevelopmentPods/Fate'
pod 'Fatal', :path => 'DevelopmentPods/Fatal'
pod 'RxMoya', :path => 'DevelopmentPods/RxMoya'
pod 'FOLDin', :path => 'DevelopmentPods/FOLDin'
pod 'Mediator', :path => 'DevelopmentPods/Mediator'
pod 'SwiftyHUD', :path => 'DevelopmentPods/SwiftyHUD'
pod 'FDNamespacer', :path => 'DevelopmentPods/FDNamespacer'
pod 'AudioService', :path => 'DevelopmentPods/AudioService'

pod 'IQKeyboardManagerSwift'

pod 'YYKit', '~> 1.0.9'
pod 'SnapKit', '~> 4.2.0'
pod 'SkeletonView', '~> 1.4.2'
pod 'RxSwift', '~> 4.4.2'
pod 'RxCocoa', '~> 4.4.2'
pod 'RxOptional', '~> 3.6.2'
pod 'RxSwiftExt', '~> 3.4.0'
pod 'MJRefresh', '~> 3.1.15.7'
pod 'SDCycleScrollView', '~> 1.75'

  target 'MVVMPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
