# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MvvmDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.0.0'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'ObjectMapper'
  pod 'RxDataSources'
  target 'MvvmDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MvvmDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
